### PR TITLE
docker-compose file for building the project using an external swarm

### PR DESCRIPTION
**Pull request by AndreeaDora**

### CODE REVIEW

**Comment by soninob** [comment]
@andreea, please sign the waver

**Comment by rqc** [comment]
Hey @AndreeaDora I thought these changes were already in `dev` branch. If so, then I think the proper thing would be to pull / merge the changes from `dev` onto `feature/integration-between-proejct-api-ui` since the former (dev) is our main branch. What do you think?

**Comment by Andreea** [comment]
Sorry you're confused, this is nota @andreea email. Do not text me again,

Thanks

**Comment by Andreea** [comment]
Sorry this is nota @AndreeaDora email. Please do not text this email again.

Thank you

**Comment by rqc** [comment]
@AndreeaDora I am merging this into the integration branch.

**Comment by Andreea** [comment]
Please, do not text again this email.

**Comment by Andreea** [comment]
Please do not text again this email.

**Pull request merged**
