### PR TITLE
Stand alone image changes

### PR DESCRIPTION
**Pull request by edagan**
New ilm-go.build dockerfile, building the image used for building ilm. Image contains golang 1.6.
New Dockerfile-sa.build to build a generic image based on debian.
Updated docker-compose.yml as build, test and deployment are now done via: buildme.sh.
  buildme.sh now supports reading environment variables for its internal parameters.
New create_env_file.sh script to create the .env file automatically. Its functionality is included in buildme.sh.

### CODE REVIEW

**Comment by rqc** [comment]
@edagan I think the devs in the team would need a walkthrough on how our new development workflow would look like now that we have these scripts. 

@AndreeaDora @borzamircea @JonathanRosado @gmatoshp

**Comment by rqc** [comment]
@edagan I issued this change in the current `docker-compose.yml` in the `dev` branch to start using our customized image of `clair`. We need to make sure that your solution also uses this: https://github.com/eedevops/shipyard/blob/dev/docker-compose.yml#L62

**Comment by edagan** [comment]
@rqc Updated to use new clair image - Thanks!

**Comment by rqc** [comment]
@edagan looks good, I'm merging.

**Pull request merged**
