### PR TITLE
Feature/tags v2 fetching

### PR DESCRIPTION
**Pull request by borzamircea**
- Added fetching for all v2 tags for an image -- working properly
- Now, layer info is missing, hence `Additional tags` are not working -- This is a WIP (spike and impolementation, if possible)

### CODE REVIEW

**Comment by soninob** [comment]
@borzamircea - please squash

**Comment by borzamircea** [comment]
On it... squashing as we speak

**Comment by borzamircea** [comment]
Squash completed

**Comment by soninob** [comment]
Thanks! Why are we supporting search in v1?

**Pull request merged**
